const restorant = [
    {
        name : "Buttermilk Pancakes",
        price : "$15.99",
        category:'breakfast',
        img :'https://vanilla-js-basic-project-8-menu.netlify.app/images/item-1.jpeg',
        text:"vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats",
    },
    {
        name : "Diner Double",
        price : "$13.99",
        category:'lunch',
        img :'https://vanilla-js-basic-project-8-menu.netlify.app/images/item-2.jpeg',
        text:"vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats",
    },
    {
        name : "Country Delight",
        price : "$14.99",
        category:'breakfast',
        img :'https://vanilla-js-basic-project-8-menu.netlify.app/images/item-4.jpeg',
        text:"vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats",
    },
    {
        name : "Godzilla Milkshake",
        price : "$12.99",
        category:'shakes',
        img :'https://nerdist.com/wp-content/uploads/2018/06/Milkshake-expensive.jpg',
        text:"vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats",
    },
    {
        name : "Egg Attack",
        price : "$23.99",
        category:'lunch',
        img :'https://vanilla-js-basic-project-8-menu.netlify.app/images/item-5.jpeg',
        text:"vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats",
    },
    {
        name : "Oreo Dream",
        price : "$17.99",
        category:'shakes',
        img :'https://vanilla-js-basic-project-8-menu.netlify.app/images/item-6.jpeg',
        text:"vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats",
    },
    {
        name : "Bacon Overflow",
        price : "$8.99",
        category:'breakfast',
        img :'https://vanilla-js-basic-project-8-menu.netlify.app/images/item-7.jpeg',
        text:"vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats",
    },
    {
        name : "American Classic",
        price : "$19.99",
        category:'lunch',
        img :'https://vanilla-js-basic-project-8-menu.netlify.app/images/item-8.jpeg',
        text:"vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats",
    },
    {
        name : "Quarantine Buddy",
        price : "$16.99",
        category:'shakes',
        img :'https://vanilla-js-basic-project-8-menu.netlify.app/images/item-9.jpeg',
        text:"vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats",
    },
    {
        name : "Steak Dinner",
        price : "$30.99",
        category:'dinner',
        img :'https://vanilla-js-basic-project-8-menu.netlify.app/images/item-10.jpeg',
        text:"vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats",
    },
]